### ISSUE TITLE
Hide help text

### ISSUE THREAD

**Issue by Shatur** [windwp/nvim-spectre#11]
Could you add the ability to hide text message?
![изображение](https://user-images.githubusercontent.com/22453358/119041621-81a68c80-b9bf-11eb-8238-58b60c8dadc5.png)
Just a boolen option to have a clean view:
![изображение](https://user-images.githubusercontent.com/22453358/119041759-b1559480-b9bf-11eb-9df7-db9e94e7aa85.png)

**Comment by windwp** [comment]
It is a little difficult to delete a line there are many hard coding number to get the search and replace text.

**Comment by Shatur95** [comment]
Oh, understand, will no be easy...
BTW, Is it possible to use virtual text feature for it?
