### ISSUE TITLE
Getting Error With Out Of The Box Setup

### ISSUE THREAD

**Issue by monsonjeremy** [windwp/nvim-spectre#12]
Thanks for the cool plugin! Really want to get it to work, but unfortunately I haven't had any luck. With a fresh install and an out of the box setup I get an error every time I try to actually perform the replacement. It works on searching, but the `sed` command seems to fail everytime. 

As you asked in another ticket I've added the logging value and captured the output.

Here is what the UI looks like (with my minimal vim config.. sorry)
<img width="1680" alt="Screen Shot 2021-05-29 at 3 45 17 PM" src="https://user-images.githubusercontent.com/8846086/120086626-424dff00-c095-11eb-824d-27ac90feb6df.png">

<details>
<summary>Here is my `minimal.vim`</summary>

```vim
call plug#begin(has('nvim') ? stdpath('data') . '/plugged' : '~/.vim/plugged')

Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-lua/popup.nvim'
Plug 'windwp/nvim-spectre'

call plug#end()

nnoremap <leader>S :lua require('spectre').open()<CR>

nnoremap <leader>sw viw:lua require('spectre').open_visual()<CR>
vnoremap <leader>s :lua require('spectre').open_visual()<CR>
nnoremap <leader>sp viw:lua require('spectre').open_file_search()<cr>

lua << EOF
  _G.__is_log =true
  require('spectre').setup()
EOF
```

</details>

Here are the log outputs:
```
[nvim-spectre] [DEBUG 15:44:04] ...re/nvim/plugged/nvim-spectre/lua/spectre/search/base.lua:104: search cwd                                                           
[nvim-spectre] [DEBUG 15:44:04] ...re/nvim/plugged/nvim-spectre/lua/spectre/search/base.lua:105: search args rg { "--color=never", "--no-heading", "--with-filename", "--line-nu
mber", "--column", "--ignore-case", "--", "TO BE REPLACED" }
[nvim-spectre] [DEBUG 15:44:14] ...re/nvim/plugged/nvim-spectre/lua/spectre/replace/sed.lua:45: replace cwd 
[nvim-spectre] [DEBUG 15:44:14] ...re/nvim/plugged/nvim-spectre/lua/spectre/replace/sed.lua:46: replace args sed { "-i", "-E", "2,2s/TO BE REPLACED/REPLACED/gi", "test.js" }
```

**Comment by windwp** [comment]
I use the same query and it work
![demo](https://user-images.githubusercontent.com/7578110/120088547-ea0e1000-c11b-11eb-8abb-2d9f02e108ff.gif)

are you try to run that command on terminal?
```
sed -i -E 2,2s/TO BE REPLACED/REPLACED/gi test.js
```
my sed version is
 sed (GNU sed) 4.7

**Comment by monsonjeremy** [comment]
I just installed `gnu-sed` after realizing that gnu-sed is the one you were expecting users to use. Even with that though I get the following:

<img width="776" alt="Screen Shot 2021-05-29 at 10 34 43 PM" src="https://user-images.githubusercontent.com/8846086/120093284-126f1d80-c0ce-11eb-85af-188532da0bc8.png">

**Comment by windwp** [comment]
@monsonjeremy  get the latest version and check again

**Comment by monsonjeremy** [comment]
Great that worked, thank you!

**Comment by monsonjeremy** [comment]
@windwp One more question, would it be possible to configure to use `sd` instead of `gnu-sed`?

See here: https://github.com/chmln/sd

**Comment by windwp** [comment]
sd use a different regex syntax for group replace it not similar to vim regex syntax. and i use that regex syntax to highlight and ensure you can run a command with that regex on vim command
so if you want to use another tool you need a function to convert  regex first
