### ISSUE TITLE
Send to `Trouble quickfix`?

### ISSUE THREAD

**Issue by macintacos** [windwp/nvim-spectre#14]
Any chance there could be integration with https://github.com/folke/trouble.nvim? You can run `:lua require"spectre.actions".send_to_qf()`, close the quickfix list, and then open it again with Trouble, but that feels a tad clunky. Would be fantastic if that were just an option that could be passed.

**Comment by windwp** [comment]
why you need to display on trouble?

I create that command send to quickfix because I can run vim command like cdo or cfdo.
