### ISSUE TITLE
Error stopping job

### ISSUE THREAD

**Issue by AckslD** [windwp/nvim-spectre#15]
Not sure I'm doing something wrong but when I try to use spectre nothing shows up in the preview and when I enter a path and leave insert mode I get the following error:
```
Error detected while processing InsertLeave Autocommands for "<buffer=3>":                                                                                                    
E5108: Error executing lua ...ck/packer/start/nvim-spectre/lua/spectre/search/base.lua:124: attempt to call method 'stop' (a nil value)
```
Any idea why this might be happening?

Looking at the code, it does check that the plenary `Job` is not `nil` but for some reason it doesn't have the method `stop`.

**Comment by windwp** [comment]
what is your setup function?
the stop function come from plenary lib so it should have if job is not nil.
are you to update plugin?

**Comment by AckslD** [comment]
I don't call `setup` actually, is that required? I only for now have a mapping to
```
:lua require("spectre").open()<CR>
```

I'm currently on 4ee33ae

**Comment by windwp** [comment]
you need to call setup.

**Comment by AckslD** [comment]
@windwp since this is only under Customisation in the README and not under Usage I assumed that it was only needed if one wants to change the default settings.

Anyway, I added it to my config but I have the same behaviour.

**Comment by windwp** [comment]
i cannot reproduce your issue.
so can you test it with a minimum config or at least provide a detail to how to get that issue.

**Comment by windwp** [comment]
sorry i found a problem you are using ripgrep 13
just update and check again
https://github.com/BurntSushi/ripgrep/issues/1892
https://github.com/nvim-telescope/telescope.nvim/issues/907

**Comment by AckslD** [comment]
Thanks for coming back to this @windwp, what requires an update? ripgrep, neovim, telescope or spectre? I currently have:
ripgrep: 13.0.0
neovim: v0.5.0-dev+1425-g7da86f55a
telescope: 6ac5ee0
spectre: 4ee33ae

**Comment by windwp** [comment]
just update spectre

**Comment by AckslD** [comment]
Yep that worked, apologies. Don't know why but when I did `PackerUpdate` it didn't update spectre for some reason, but I had to manually pull to get the latest commits
