### ISSUE TITLE
Option To disable icons

### ISSUE THREAD

**Issue by timsofteng** [windwp/nvim-spectre#16]
Hello. Could you provide please option like `disable_icons` to disable all icons and change it to some default regular non-icons signs for users who don't use `devicons`?

P.s many thanks for this great plugin

**Comment by windwp** [comment]
you can update plugin it have an option   color_devicons = true, check readme

**Comment by timsofteng** [comment]
> you can update plugin
> it have an option color_devicons = true
> check readme

I've added it but have this weird symbols:
![image](https://user-images.githubusercontent.com/51912173/122256470-c565b680-ced7-11eb-93d0-fd8d417eb637.png)
