### ISSUE TITLE
Toggle panel

### ISSUE THREAD

**Issue by Shatur** [windwp/nvim-spectre#18]
In VSCode, you can toggle the search panel to return to it later.

It would be possible to add an extra option inside the `open` function that would open the previous buffer.

As alternative we could just have a separate command that allows to show / hide Spectre.

**Comment by piersolenski** [comment]
So sad 😿

**Comment by tortoise10h** [comment]
I think it will be a quite good feature, why it wasn't taken into account tho?

**Comment by itsFrank** [comment]
This is an old thread, but I believe I managed to solve this by using spectre state.

**Warning**: I am not sure if I am using `spectre.state` is officially supported, it is possible that a future version of spectre breaks this keymap; however, for now this seems to work quite well for me with the latest version:

```lua
vim.keymap.set("n", "<leader>sp", function()
    local spectre = require("spectre")
    local spectre_state = require("spectre.state")
    
    local is_open = false
    if spectre_state.bufnr ~= nil then
        local wins = vim.fn.win_findbuf(spectre_state.bufnr)
        if next(wins) ~= nil then -- check if wins is empty
            is_open = true
        end
    end

    if is_open then
        spectre.close()
    else
        spectre.open()
    end
end)
```

I have not yet figured out how to make it work with resume last search however. But for now this is perfect for 99% of my workflows.

You could also do this without relying on `spectre.state` by searching for buffers with the string `"spectre"` in their name. However that might lead to false positives if project files have that string as well, this should also be a bit faster too.

Hopefully this helps someone! (also hoping that this is already a supported feature and someone corrects me!)
