### ISSUE TITLE
Provide lua example on keymappings?

### ISSUE THREAD

**Issue by thepenguinthatwants** [windwp/nvim-spectre#19]
Hi,
can you provide example how to set the mapping using lua instead of vimscript?
As the way in lua are very different but I cant figure out how to set it based on the documentation.

So far this works but feels bit hacky.
```
cmd([[
nnoremap <leader>HH :lua require('spectre').open()<CR>
"search current word
nnoremap <leader>Hw viw:lua require('spectre').open_visual()<CR>
vnoremap <leader>H :lua require('spectre').open_visual()<CR>
"  search in current file
nnoremap <leader>Hp viw:lua require('spectre').open_file_search()<cr>
]])


```

**Comment by windwp** [comment]
https://github.com/nanotee/nvim-lua-guide#defining-mappings
you should check it
