### ISSUE TITLE
Do not work on Windows

### ISSUE THREAD

**Issue by maxxnino** [windwp/nvim-spectre#21]
I try _G.__is_log =true

I got this log
> rg --color=never --no-heading --with-filename --line-number --column -g **luaplugins.lua** --ignore-case -- local .

The correct path is **lua/plugins.lua**, but some how it become **luaplugins.lua**, I don't know what a problem is
It's work perfectly if the file not in any folder

**Comment by windwp** [comment]
Sorry i don't use window pc now

**Comment by maxxnino** [comment]
I got the same behavior with packer too, https://github.com/wbthomason/packer.nvim/issues/418
And now they fixed it, maybe it's the same with the bug above
