### ISSUE TITLE
More options for opening search result

### ISSUE THREAD

**Issue by asgeo1** [windwp/nvim-spectre#25]
After I do a search, I can use `<CR>` to open the result, which by default will open it in the window I started the search from.

This is a bit annoying as now I've lost my buffer I was working on.

I was hoping there would be mappings like

 - `<Ctrl+o>` open in horizontal split
 - `<Ctrl+v>` open in vertical split
 - `<Ctrl+t>` open in new tab

so I don't affect the window I did the search in.

Is there a way to configure this?

The work around is to send the search results to the quickfix window, and then use those mapings from there. But it seems like an extra step for no reason.

**Comment by windwp** [comment]
i don't usually do that  if i open 10 file with split then it need 10 split windown .
but if you really want to have that mapping you can check the api to get current file on cursor then do whatever you want.

**Comment by asgeo1** [comment]
When I'm searching for something to edit, it's usually something specific, so I only endup opening one or two splits. I wouldn't open 10 splits in practice, that's too many. I'd do something else like use the quickfix window in that case.

I was previously using the `ctrlsf.vim` plugin, which has similar mappings for opening results in splits or tabs.

I'm happy to create my own mappings for this. I just assumed other people would want to do the same thing and thought it might be worth putting in the plugin itself.

**Comment by asgeo1** [comment]
FWIW, here are the mappings I created that will open results in split windows or new tabs.

```lua
  require("spectre").setup {
    mapping={
      ['open_in_vsplit'] = {
          map = "<c-v>",
          cmd = "<cmd>lua vim.cmd('vsplit ' .. require('spectre.actions').get_current_entry().filename)<CR>",
          desc = "open in vertical split"
      },
      ['open_in_split'] = {
          map = "<c-s>",
          cmd = "<cmd>lua vim.cmd('split ' .. require('spectre.actions').get_current_entry().filename)<CR>",
          desc = "open in horizontal split"
      },
      ['open_in_tab'] = {
          map = "<c-t>",
          cmd = "<cmd>lua vim.cmd('tab split ' .. require('spectre.actions').get_current_entry().filename)<CR>",
          desc = "open in new tab"
      },
    }
  }

```
