### ISSUE TITLE
Deleting multiple matches at once

### ISSUE THREAD

**Issue by brandoncc** [windwp/nvim-spectre#3]
Thanks for this cool plugin!

I'm not sure, but I think I found a bug (or I am mis-using a feature). From what I can tell, `dd` on a search result toggles it (turns it active/inactive). If I make a visual selection block, then press `d`, the lines are actually deleted (I think this is my possible mis-use of the feature). If I press `dd` again after doing that, the current line is replaced with a different line (I think this is the bug).

Should I be able to do visual selection blocks and delete that way?

Thanks.

**Comment by windwp** [comment]
yes it is missing feature .dd is only work on normal mode now 
i will update it later

**Comment by windwp** [comment]
I fixed it

**Comment by brandoncc** [comment]
Awesome, it is working great! Thank you :-)
