### ISSUE TITLE
Do not work on Windows

### ISSUE THREAD

**Issue by Shatur** [windwp/nvim-spectre#5]
When searching for something on Windows, the results are always empty. But it works correctly on Linux. Possibly some kind of problem with the paths?

**Comment by windwp** [comment]
Is  telescope working on your neovim window 
i don't use window now so i can't test but i think it will work if you install rg and sed.

**Comment by Shatur95** [comment]
> Is telescope working on your neovim window

Yes.

>  i don't use window now so i can't test but i think it will work if you install rg and sed.

I have `rg` and `sed` installed.
But have no search results with correct current working directory set:
![изображение](https://user-images.githubusercontent.com/22453358/115575483-44b97e00-a2cb-11eb-8a4c-b2164ba492d8.png)

**Comment by windwp** [comment]
_G.__is_log =true

 can you put that on top of your init.lua and reopen to show the log

**Comment by Shatur95** [comment]
```
|| [plenary] [DEBUG 18:34:41] ...kpluginsstart^@vim-spectreluaspectresearch^Hase.lua:66: search cwd 
|| [plenary] [DEBUG 18:34:41] ...kpluginsstart^@vim-spectreluaspectresearch^Hase.lua:67: search args rg { "--color=never", "--no-heading", "--with-filename", "--line-number", "--column", "-g", "", "--ignore-case", "--", "nvim" }
```

**Comment by vitpekarek** [comment]
Hello, I have same similar issue even after you fixed cmd for ripgrep.

Log:
`
[DEBUG 5/28/2021 6:43:14 PM] ...ck\packer\start\nvim-spectre\lua\spectre\search\base.lua:105: search args rg { "--color=never", "--no-heading", "--with-filename", "--line-number", "--column", "--ignore-case", "--", "test" }
`

But when I try command manually in command line it is working without any problem...

`rg --color=never --no-heading --with-filename --line-number --column --ignore-case -- test`

**Comment by Shatur95** [comment]
@vitpekarek, the issue in plenary: https://github.com/nvim-lua/plenary.nvim/issues/146

**Comment by windwp** [comment]
you can try to use ag search

**Comment by windwp** [comment]
@Shatur  I think i found a problem in window you need to put the "./" to use it on stdin search but  on linux you don't need that.
when ripgrep update to version 13.0 it is require on linux and mac .

https://github.com/nvim-telescope/telescope.nvim/issues/907

**Comment by Shatur** [comment]
> @Shatur I think i found a problem in window you need to put the "./" to use it on stdin search but on linux you don't need that.

Wow, you are right, it works now!

**Comment by maxxnino** [comment]
I got this log
> rg --color=never --no-heading --with-filename --line-number --column -g **luaplugins.lua** --ignore-case -- local .

the correct path is **lua/plugins.lua**, but some how it become **luaplugins.lua**, I don't know what a problem is
