### ISSUE TITLE
Unfold all results

### ISSUE THREAD

**Issue by Shatur95** [windwp/nvim-spectre#7]
On demo.gif  all the results are displayed unfolded: ![demo.gif](https://github.com/windwp/nvim-spectre/raw/master/images/demo.gif).
But I have all results folded by default and I have to expand them:
![изображение](https://user-images.githubusercontent.com/22453358/115991514-67041200-a5d1-11eb-87e8-194fe43b8882.png)

How can you achieve the behavior as on your showcase GIF?

**Comment by windwp** [comment]
it is your vim setting you can open another file have fold to check

**Comment by Shatur95** [comment]
Thank you, added `vim.o.foldenable = false` to my `init.lua`.
