### ISSUE TITLE
Remove gif in images?

### ISSUE THREAD

**Issue by ray-x** [windwp/nvim-spectre#8]
great plugin.
One suggestion is remove gif from the plugin and clean up the .git (may need to purge all history to reduce the .git size). You can provide a URL of the gif from wiki/gist in the Readme.
The repo is 13MB ATM

**Comment by windwp** [comment]
I will not add more image on this repo.
I am not familiar with change history on git and force push is not my favorite command so thank for your suggestion

**Comment by ray-x** [comment]
One way is re-run git init and it will clean all git history. Yes, it is a bummer. Another way would be to patch everything after gif was created.
Personally, I would do it earlier rather than late. As each time you update the gif when you have a feature update, it will add an extra 6.5MB in your repo.
